### ISSUE TITLE
Class 'rex_yform_value_readtable' not found

### ISSUE THREAD

**Issue by joachimdoerr** [yakamara/redaxo_yform#119]
```
"Error" thrown in /Volumes/Marvin/Repos/r5/redaxo/src/addons/yform/lib/yform.php on line 549
Class 'rex_yform_value_readtable' not found

#0 /Volumes/Marvin/Repos/r5/redaxo/src/addons/yform/pages/overview.php(77): rex_yform::showHelp(true, true)
#1 /Volumes/Marvin/Repos/r5/redaxo/src/addons/yform/pages/index.php(3): include('/Volumes/Marvin...')
#2 /Volumes/Marvin/Repos/r5/redaxo/src/core/lib/packages/package.php(228): include('/Volumes/Marvin...')
#3 /Volumes/Marvin/Repos/r5/redaxo/src/core/lib/be/controller.php(456): rex_package->includeFile('pages/index.php', Array)
#4 /Volumes/Marvin/Repos/r5/redaxo/src/core/lib/be/controller.php(403): rex_be_controller::includePath('/Volumes/Marvin...')
#5 /Volumes/Marvin/Repos/r5/redaxo/src/core/backend.php(138): rex_be_controller::includeCurrentPage()
#6 /Volumes/Marvin/Repos/r5/redaxo/src/core/boot.php(105): require('/Volumes/Marvin...')
#7 /Volumes/Marvin/Repos/r5/redaxo/index.php(9): require('/Volumes/Marvin...')
#8 {main}

activate safe mode
```

**Comment by joachimdoerr** [comment]
Cache leeren nach der Installation, danach kommt der Fehler nicht mehr.

**Comment by alexplusde** [comment]
Duplikat https://github.com/yakamara/redaxo_yform/issues/107
