### ISSUE TITLE
Table Manager: Suche aktiv + kein Suchfeld = Fehler

### ISSUE THREAD

**Issue by alexplusde** [yakamara/redaxo_yform#147]
Wenn die Suche aktiv ist, aber keine Felder die Freigabe zum Durchsuchen haben, kommt es zu einem Fehler.

```
Error while executing statement ""! SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty
#0 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/addons/yform/lib/yform/value/select_sql.php(171): rex_sql->setQuery(NULL)
#1 [internal function]: rex_yform_value_select_sql::getSearchField(Array)
#2 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/addons/yform/plugins/manager/lib/yform/manager/search.php(82): call_user_func('rex_yform_value...', Array)
#3 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(134): rex_yform_manager_search->getForm()
#4 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/addons/yform/plugins/manager/pages/data_edit.php(21): rex_yform_manager->getDataPage()
#5 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/addons/yform/pages/index.php(3): include('/home/netsh1084...')
#6 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/core/lib/packages/package.php(228): include('/home/netsh1084...')
#7 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/core/lib/be/controller.php(456): rex_package->includeFile('pages/index.php', Array)
#8 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/core/lib/be/controller.php(403): rex_be_controller::includePath('/home/netsh1084...')
#9 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/core/backend.php(138): rex_be_controller::includeCurrentPage()
#10 /home/netsh108412/html/---.de/rex5.---.de/redaxo/src/core/boot.php(105): require('/home/netsh1084...')
#11 /home/netsh108412/html/---.de/rex5.---.de/redaxo/index.php(9): require('/home/netsh1084...')
#12 {main}
```

**Comment by dergel** [comment]
hmm.. leide rkann ich das doch nicht nachvollziehen.. Bei mir klappt es. Der Fehler sieht auch anders aus .. kannst Du schauen ob das select_sql Feld auch richtig ausgefüllt ist ?

**Comment by dergel** [comment]
ich denke mal, dass ist was anderes.. sofern ich mich täusche - gerne wieder issue aufmachen.
