### ISSUE TITLE
Installer Error yform 1.0-beta3

### ISSUE THREAD

**Issue by isospin** [yakamara/redaxo_yform#43]
Wollte gerade via Installer von beta2 auf beta3 updaten:

```
InvalidArgumentException thrown in /me/full/path/redaxo/src/core/lib/util/finder.php on line 50
Folder "/me/full/path/redaxo/src/addons/yform/data" not found!

#0 /me/full/path/redaxo/src/core/lib/util/dir.php(71): rex_finder::factory('/is/htdocs/wp11...')
#1 /me/full/path/redaxo/src/addons/.new.yform/update.php(3): rex_dir::copy('/is/htdocs/wp11...', '/is/htdocs/wp11...')
#2 /me/full/path/redaxo/src/core/lib/packages/package.php(226): include('/is/htdocs/wp11...')
#3 /me/full/path/redaxo/src/addons/install/lib/api_package_update.php(57): rex_package->includeFile('../.new.yform/u...')
#4 /me/full/path/redaxo/src/addons/install/lib/api_package_download.php(40): rex_api_install_package_update->doAction()
#5 /me/full/path/redaxo/src/core/lib/api_function.php(130): rex_api_install_package_download->execute()
#6 /me/full/path/redaxo/src/core/backend.php(131): rex_api_function::handleCall()
#7 /me/full/path/redaxo/src/core/boot.php(105): require('/is/htdocs/wp11...')
#8 /me/full/path/redaxo/index.php(9): require('/is/htdocs/wp11...')
#9 {main}
```

REDAXO 5.0.1
PHP 5.6.17

**Comment by dergel** [comment]
stimmt.. fehler ist behoben.. beta3 entfernt und beta4 eingesetzt. danke für die Info ..
